version: "3"
services:

  nginx:
    restart: unless-stopped
    networks:
      - traefik_webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_webgateway"
      - ${NGINX_TRAEFIK_RULE:-traefik.http.routers.my-router.rule=Host(`api.localhost`)}
      - ${NGINX_TRAEFIK_ENRTYPOINTS:-traefik.http.routers.my-router.entrypoints=web}
      - ${NGINX_TRAEFIK_LOADBALANCER_PORT:-traefik.http.services.my-service.loadbalancer.server.port=80}

networks:
  traefik_webgateway:
    external: true

