version: "3"
services:

  nginx:
    restart: unless-stopped
    networks:
      - traefik_webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.http.routers.snapwire_laradoc.rule=Host(`api.snapwire.eltex.dev`)"
      - "traefik.http.routers.snapwire_laradoc.entrypoints=web"
      - "traefik.http.services.snapwire_laradoc.loadbalancer.server.port=80"

networks:
  traefik_webgateway:
    external: true

